### PR TITLE
Note reports that this can take some minutes to complete

### PR DESCRIPTION
**Pull request by edwardcallahan**

### CODE REVIEW

**Comment by piyushknoldus** [comment]
actually this should come under the `watch conduct agents` after issuing the `pgrep -f "conductr.agent.ip=192.168.10.3" | xargs kill -s SIGCONT` as it is the agent nodes what took a little longer to come up.
We can add the content at line number 679.

**Comment by edwardcallahan** [comment]
That makes more sense. Thanks. But it is line 829, as such now, yes?

**Comment by TimMoore** [comment]
@edwardcallahan should we merge this?

**Comment by edwardcallahan** [comment]
Yes, please.

**Review by TimMoore — APPROVED** [review]

**Pull request merged**
