### PR TITLE
Prefer YAML

### PR DESCRIPTION
**Pull request by guizmaii**
YAML is (in my opinion) way more readable than JSON and there's a `jq` wrapper, named `yq` that handles YAML.

What do you think about this ?

### CODE REVIEW

**Comment by ignasi35** [comment]
@longshorej & @fsat would you be able to review this?

**Comment by longshorej** [comment]
Thanks for the contribution @guizmaii. I'm not too sure about this .. I rather like the simplicity of JSON. YAML is a pretty complex beast... (from an implementation perspective). Perhaps we need to take a vote :stuck_out_tongue:

**Comment by paulczar** [comment]
Kubernetes manifests are generally written by a person, while the whitespacing of YAML can be hard to read at times, its overall much easier for a person to read, write and understand.  

The biggest reason to use YAML for the kubernetes manifests is it allows us to utilize comments inside the manifests which will be very useful for describing what the various sections do and how ( for instance where we declare things that are helpful in the clustering and service discovery bits for akka streams ).

**Comment by guizmaii** [comment]
Totally agree with @paulczar.

**Comment by TimMoore** [comment]
We're taking a new approach to this, based on the new [Lightbend Orchestration for Kubernetes](https://developer.lightbend.com/docs/lightbend-orchestration-kubernetes/latest/) tooling.

See https://github.com/lagom/lagom-java-sbt-chirper-example/pull/2

(Note that it is in a different repository: we are splitting the sbt and Maven examples because this project was getting to be too complex.)

**Pull request closed without merging**
