### PR TITLE
JVM flags

### PR DESCRIPTION
**Pull request by guizmaii**

### CODE REVIEW

**Review by longshorej — CHANGES_REQUESTED** [review]
Thanks for this @guizmaii -- can you also add it to the Maven configuration (and update Scala there too)?

I'll do a separate PR for the K8s-related changes.

**Comment by guizmaii** [comment]
Ok i'll do that. Thanks for the feeback

**Comment by guizmaii** [comment]
@longshorej I added the flags in the maven configurations but I can't find where the Scala version is set in maven. I think it isn't set anywhere (maybe because it's a Java app ?)

**Review by longshorej — APPROVED** [review]
Thanks @guizmaii!

**Pull request merged**
