### PR TITLE
Bump to Lagom 1.3.8

### PR DESCRIPTION
**Pull request by ignasi35**

### CODE REVIEW

**Comment by ignasi35** [comment]
@fsat upgrading to lagom 1.3.8 bumps the underlying logback version. Let us know if merging this PR causes side effects on the logging setup.

**Comment by longshorej** [comment]
I think we need to upgrade Maven as well - `project/properties/lagom.version` in the root `pom.xml`.

**Comment by ignasi35** [comment]
Good call! Updated.

It's not tracked on our release script so I'll update it there too so we don't forget again.

**Review by TimMoore — APPROVED** [review]

**Review by longshorej — APPROVED** [review]
LGTM

* Installed to Minikube
* Scaled `ss/friendservice` to 3 replicas
* Deleted `po/friendservice-0`
* Verified with `kubectl logs` that when `ss/friendservice` recreated `po/friendservice-0`, it joined the cluster correctly.

**Comment by fsat** [comment]
I've also tested this on ConductR using Maven and SBT, and all is working as expected.

**Pull request merged**
