### PR TITLE
Update Lagom to 1.3.6

### PR DESCRIPTION
**Pull request by TimMoore**

### CODE REVIEW

**Comment by TimMoore** [comment]
CC: @fsat. I don't think it will affect your work negatively, but just in case.

**Comment by fsat** [comment]
@TimMoore - I think #72 should not be affected since I'm changing the `packageBin` target which comes from SBT web instead of Lagom.

However, to be on the safe side I'm happy to do another round of manual test for #72 if we can merge #71 first - wdyt?

**Comment by TimMoore** [comment]
@fsat it's OK I think we can merge #72 first and then I can rebase this change and test again. I'd like to run through the tests you did, anyway, just so I know the procedure.

**Comment by TimMoore** [comment]
I rebased and ran through all of the tests listed in #72. Everything looks good.

**Comment by fsat** [comment]
Yay! 👍

**Pull request merged**
