### PR TITLE
Fix inconsistencies and missing wait script

### PR DESCRIPTION
**Pull request by longshorej**
* `DeployKubernetesMinikube.md` is now basically a summary of the TechHub guide and links to it
* Added missing `kubectl-wait-for-pods` script that TechHub guide references.

### CODE REVIEW

**Review by ignasi35 — APPROVED** [review]
I haven't tested `install -all` woth the changes included here. I haven't reviewed the deployment guide in this PR.

I've tested the step be step install (which uses the `kubectl-wait-for-pods`) successfully.

**Comment by guizmaii** [comment]
I think that the `DeployKubernetesMinikube.md` doc could be confusing because it creates a second source of truth after the TechHub guide.

IMHO, the best is just to delete it and add the link to the guide in the README.md

**Comment by guizmaii** [comment]
How did you do that `I've tested the step be step install (which uses the kubectl-wait-for-pods) successfully.` @ignasi35 ?

**Comment by ignasi35** [comment]
@guizmaii I destroyed my minikube cluster and started from scratch. I followed https://developer.lightbend.com/guides/k8s-microservices/ though.

From the developer guide I only needed three steps:

1. checkout chirper in `master`
2. create [a new, empty minikube cluster](https://developer.lightbend.com/guides/k8s-microservices/#minikube)
3. use the [install all script](https://developer.lightbend.com/guides/k8s-microservices/#deploying-using-minikube).


 - - -  

Then, when testing this PR I did follow the step by step process described in the guide to make sure the fixes in `kubectl-wait-for-pods` worked.

**Comment by guizmaii** [comment]
Ok sorry my question was stupid. I thought you said that you succeeded to do the step by step install without this PR.

**Comment by ignasi35** [comment]
> Ok sorry my question was stupid

No such thing as stupid questions. My original comment lead to missinterpretation so thanks for pointing it out. :-)

**Comment by guizmaii** [comment]
What about my other comment: 
```
I think that the DeployKubernetesMinikube.md doc could be confusing because it creates a second source of truth after the TechHub guide.

IMHO, the best is just to delete it and add the link to the guide in the README.md
```

???

**Pull request merged**
