### PR TITLE
wrong import

### PR DESCRIPTION
**Pull request by jorgheymans**

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @jorgheymans,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by jorgheymans** [comment]
signed

**Comment by jorgheymans** [comment]
not sure why travis is failing ?

**Comment by octonato** [comment]
Seems to be a flaky test. I had restarted the job already once with the same results. 
Just restarted once again. Fingers crossed.

**Comment by ignasi35** [comment]
Failed again. Restarted again. 😒

**Comment by ignasi35** [comment]
thanls @jorgheymans

**Comment by octonato** [comment]
Test passed, code merged! 
Thanks @jorgheymans

**Comment by octonato** [comment]
correction:
test passed, code merged, test broken again! :-(

**Pull request merged**
