### PR TITLE
Lagom 1.4.0

### PR DESCRIPTION
**Pull request by octonato**
Supersedes #88

### CODE REVIEW

**Comment by longshorej** [comment]
I'm working on getting this up and running with Platform Tooling. I think I'll be ready to approve tomorrow, just found a few bugs on our side with 1.4 support that I'd like to fix first.

**Comment by longshorej** [comment]
Okay, deployed this to K8s and the interesting bits are working. Something's broken with the assets though, webjar routes are returning 404 for some assets. See attached (happens locally with `runAll` as well)

**Comment by longshorej** [comment]
Okay, I pushed a commit that fixes the assets issue to your branch @renatocaval. This is looking good to me and is working locally and on Minikube.

**Review by longshorej — APPROVED** [review]
LGTM, only thought is maybe we should squash commits. I'm good either way.

**Comment by octonato** [comment]
@longshorej thanks for looking that up and fixing it. 
And yes, squash all the things!

(btw, we always squash the PRs because it makes it cherry-pickable)

**Review by TimMoore — APPROVED** [review]

**Pull request merged**
