### PR TITLE
Upgrade to SBT ConductR 2.1.10

### PR DESCRIPTION
**Pull request by fsat**

### CODE REVIEW

**Comment by fsat** [comment]
Manually tested Chirper functionality with locally built ConductR sandbox - everything is in working order.

**Setup**
- Start sandbox `sandbox run 0.1.0`
- Load all the bundles, including recently released Cassandra bundle. Cassandra bundle is loaded first due to issue #24.

**Result**
Verified the following functionality to be in working order via browser:
- Login
- Logout
- Add a friend
- Activity Stream
- Publishing new Chirp

**Comment by fsat** [comment]
Markes as wip for now - still need to validate the use of `install` task from SBT ConductR.

**Comment by fsat** [comment]
The `install` command has managed to deploy all required bundles into the ConductR sandbox.

Unfortunately issue #24 is still present, so the `install` command may fail due to this issue.

**Comment by TimMoore** [comment]
@fsat I see that sbt-conductr is up to 2.1.13 now. Should this PR be updated to the latest?

**Comment by huntc** [comment]
It has been a moving target over the past day or so!

**Comment by TimMoore** [comment]
It's now using 2.1.16

**Pull request closed without merging**
