### PR TITLE
WIP - DO NOT MERGE - Lagom 1.4

### PR DESCRIPTION
**Pull request by longshorej**

### CODE REVIEW

**Comment by octonato** [comment]
@longshorej added some updates to this open PR. 
Conflict is resolved and I can run it locally using a locally built Lagom 1.4.0.

**Comment by TimMoore** [comment]
It looks like there are a number of unrelated changes in this pull request now. Can we have one that _only_ updates to Lagom 1.4?

Other than making it easier to review, it will also be helpful for Lagom users who are updating to see an example of the changes that were required. Adding in unrelated changes makes that more confusing.

**Comment by octonato** [comment]
I'm closing this one and sending a new starting from master to avoid huge diff. This one had the master merged into it because of conflicts resulting in lots of file changes that were not relevant.

**Comment by octonato** [comment]
Superseded by #105

**Pull request closed without merging**
